// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: proto/ticket_reservation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Seat          uint32                 `protobuf:"varint,5,opt,name=seat,proto3" json:"seat,omitempty"`
	Section       string                 `protobuf:"bytes,6,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_proto_ticket_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_proto_ticket_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *UserDetails) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserDetails) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserDetails) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *UserDetails) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type ReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketNo       *uint64                `protobuf:"varint,1,opt,name=ticket_no,json=ticketNo,proto3,oneof" json:"ticket_no,omitempty"`
	FromCode       string                 `protobuf:"bytes,2,opt,name=from_code,json=fromCode,proto3" json:"from_code,omitempty"`
	ToCode         string                 `protobuf:"bytes,3,opt,name=to_code,json=toCode,proto3" json:"to_code,omitempty"`
	PricePaid      uint64                 `protobuf:"varint,4,opt,name=price_paid,json=pricePaid,proto3" json:"price_paid,omitempty"`
	PassengerCount uint64                 `protobuf:"varint,5,opt,name=passenger_count,json=passengerCount,proto3" json:"passenger_count,omitempty"`
	Passengers     []*UserDetails         `protobuf:"bytes,6,rep,name=passengers,proto3" json:"passengers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationRequest) Reset() {
	*x = ReservationRequest{}
	mi := &file_proto_ticket_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRequest) ProtoMessage() {}

func (x *ReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRequest.ProtoReflect.Descriptor instead.
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *ReservationRequest) GetTicketNo() uint64 {
	if x != nil && x.TicketNo != nil {
		return *x.TicketNo
	}
	return 0
}

func (x *ReservationRequest) GetFromCode() string {
	if x != nil {
		return x.FromCode
	}
	return ""
}

func (x *ReservationRequest) GetToCode() string {
	if x != nil {
		return x.ToCode
	}
	return ""
}

func (x *ReservationRequest) GetPricePaid() uint64 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *ReservationRequest) GetPassengerCount() uint64 {
	if x != nil {
		return x.PassengerCount
	}
	return 0
}

func (x *ReservationRequest) GetPassengers() []*UserDetails {
	if x != nil {
		return x.Passengers
	}
	return nil
}

type ReservationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketNo       uint64                 `protobuf:"varint,1,opt,name=ticket_no,json=ticketNo,proto3" json:"ticket_no,omitempty"`
	FromCode       string                 `protobuf:"bytes,2,opt,name=from_code,json=fromCode,proto3" json:"from_code,omitempty"`
	ToCode         string                 `protobuf:"bytes,3,opt,name=to_code,json=toCode,proto3" json:"to_code,omitempty"`
	PricePaid      uint64                 `protobuf:"varint,4,opt,name=price_paid,json=pricePaid,proto3" json:"price_paid,omitempty"`
	PassengerCount uint64                 `protobuf:"varint,5,opt,name=passenger_count,json=passengerCount,proto3" json:"passenger_count,omitempty"`
	Passengers     []*UserDetails         `protobuf:"bytes,6,rep,name=passengers,proto3" json:"passengers,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_proto_ticket_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ReservationResponse) GetTicketNo() uint64 {
	if x != nil {
		return x.TicketNo
	}
	return 0
}

func (x *ReservationResponse) GetFromCode() string {
	if x != nil {
		return x.FromCode
	}
	return ""
}

func (x *ReservationResponse) GetToCode() string {
	if x != nil {
		return x.ToCode
	}
	return ""
}

func (x *ReservationResponse) GetPricePaid() uint64 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *ReservationResponse) GetPassengerCount() uint64 {
	if x != nil {
		return x.PassengerCount
	}
	return 0
}

func (x *ReservationResponse) GetPassengers() []*UserDetails {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *ReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ticket_reservation_proto protoreflect.FileDescriptor

const file_proto_ticket_reservation_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/ticket_reservation.proto\x12\x12ticket_reservation\"\xa8\x01\n" +
	"\fuser_details\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04seat\x18\x05 \x01(\rR\x04seat\x12\x18\n" +
	"\asection\x18\x06 \x01(\tR\asection\"\x84\x02\n" +
	"\x12ReservationRequest\x12 \n" +
	"\tticket_no\x18\x01 \x01(\x04H\x00R\bticketNo\x88\x01\x01\x12\x1b\n" +
	"\tfrom_code\x18\x02 \x01(\tR\bfromCode\x12\x17\n" +
	"\ato_code\x18\x03 \x01(\tR\x06toCode\x12\x1d\n" +
	"\n" +
	"price_paid\x18\x04 \x01(\x04R\tpricePaid\x12'\n" +
	"\x0fpassenger_count\x18\x05 \x01(\x04R\x0epassengerCount\x12@\n" +
	"\n" +
	"passengers\x18\x06 \x03(\v2 .ticket_reservation.user_detailsR\n" +
	"passengersB\f\n" +
	"\n" +
	"_ticket_no\"\x8a\x02\n" +
	"\x13ReservationResponse\x12\x1b\n" +
	"\tticket_no\x18\x01 \x01(\x04R\bticketNo\x12\x1b\n" +
	"\tfrom_code\x18\x02 \x01(\tR\bfromCode\x12\x17\n" +
	"\ato_code\x18\x03 \x01(\tR\x06toCode\x12\x1d\n" +
	"\n" +
	"price_paid\x18\x04 \x01(\x04R\tpricePaid\x12'\n" +
	"\x0fpassenger_count\x18\x05 \x01(\x04R\x0epassengerCount\x12@\n" +
	"\n" +
	"passengers\x18\x06 \x03(\v2 .ticket_reservation.user_detailsR\n" +
	"passengers\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status2\xbd\x02\n" +
	"\x11TicketReservation\x12b\n" +
	"\rReserveTicket\x12&.ticket_reservation.ReservationRequest\x1a'.ticket_reservation.ReservationResponse\"\x00\x12a\n" +
	"\fModifyTicket\x12&.ticket_reservation.ReservationRequest\x1a'.ticket_reservation.ReservationResponse\"\x00\x12a\n" +
	"\fCancelTicket\x12&.ticket_reservation.ReservationRequest\x1a'.ticket_reservation.ReservationResponse\"\x00B5Z3github.com/Akash-private/Cloudbees_code/proto;protob\x06proto3"

var (
	file_proto_ticket_reservation_proto_rawDescOnce sync.Once
	file_proto_ticket_reservation_proto_rawDescData []byte
)

func file_proto_ticket_reservation_proto_rawDescGZIP() []byte {
	file_proto_ticket_reservation_proto_rawDescOnce.Do(func() {
		file_proto_ticket_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticket_reservation_proto_rawDesc), len(file_proto_ticket_reservation_proto_rawDesc)))
	})
	return file_proto_ticket_reservation_proto_rawDescData
}

var file_proto_ticket_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ticket_reservation_proto_goTypes = []any{
	(*UserDetails)(nil),         // 0: ticket_reservation.user_details
	(*ReservationRequest)(nil),  // 1: ticket_reservation.ReservationRequest
	(*ReservationResponse)(nil), // 2: ticket_reservation.ReservationResponse
}
var file_proto_ticket_reservation_proto_depIdxs = []int32{
	0, // 0: ticket_reservation.ReservationRequest.passengers:type_name -> ticket_reservation.user_details
	0, // 1: ticket_reservation.ReservationResponse.passengers:type_name -> ticket_reservation.user_details
	1, // 2: ticket_reservation.TicketReservation.ReserveTicket:input_type -> ticket_reservation.ReservationRequest
	1, // 3: ticket_reservation.TicketReservation.ModifyTicket:input_type -> ticket_reservation.ReservationRequest
	1, // 4: ticket_reservation.TicketReservation.CancelTicket:input_type -> ticket_reservation.ReservationRequest
	2, // 5: ticket_reservation.TicketReservation.ReserveTicket:output_type -> ticket_reservation.ReservationResponse
	2, // 6: ticket_reservation.TicketReservation.ModifyTicket:output_type -> ticket_reservation.ReservationResponse
	2, // 7: ticket_reservation.TicketReservation.CancelTicket:output_type -> ticket_reservation.ReservationResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ticket_reservation_proto_init() }
func file_proto_ticket_reservation_proto_init() {
	if File_proto_ticket_reservation_proto != nil {
		return
	}
	file_proto_ticket_reservation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticket_reservation_proto_rawDesc), len(file_proto_ticket_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ticket_reservation_proto_goTypes,
		DependencyIndexes: file_proto_ticket_reservation_proto_depIdxs,
		MessageInfos:      file_proto_ticket_reservation_proto_msgTypes,
	}.Build()
	File_proto_ticket_reservation_proto = out.File
	file_proto_ticket_reservation_proto_goTypes = nil
	file_proto_ticket_reservation_proto_depIdxs = nil
}
