// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: proto/ticket_reservation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketReservation_ReserveTicket_FullMethodName = "/ticket_reservation.TicketReservation/ReserveTicket"
	TicketReservation_ModifyTicket_FullMethodName  = "/ticket_reservation.TicketReservation/ModifyTicket"
	TicketReservation_CancelTicket_FullMethodName  = "/ticket_reservation.TicketReservation/CancelTicket"
	TicketReservation_GetAllTickets_FullMethodName = "/ticket_reservation.TicketReservation/GetAllTickets"
)

// TicketReservationClient is the client API for TicketReservation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketReservationClient interface {
	// A simple RPC.
	//
	// Obtains the MessageResponse at a given position.
	ReserveTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error)
	ModifyTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error)
	CancelTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error)
	GetAllTickets(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AllTicketsResponse, error)
}

type ticketReservationClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketReservationClient(cc grpc.ClientConnInterface) TicketReservationClient {
	return &ticketReservationClient{cc}
}

func (c *ticketReservationClient) ReserveTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservationResponse)
	err := c.cc.Invoke(ctx, TicketReservation_ReserveTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketReservationClient) ModifyTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservationResponse)
	err := c.cc.Invoke(ctx, TicketReservation_ModifyTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketReservationClient) CancelTicket(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservationResponse)
	err := c.cc.Invoke(ctx, TicketReservation_CancelTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketReservationClient) GetAllTickets(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*AllTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllTicketsResponse)
	err := c.cc.Invoke(ctx, TicketReservation_GetAllTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketReservationServer is the server API for TicketReservation service.
// All implementations must embed UnimplementedTicketReservationServer
// for forward compatibility.
type TicketReservationServer interface {
	// A simple RPC.
	//
	// Obtains the MessageResponse at a given position.
	ReserveTicket(context.Context, *ReservationRequest) (*ReservationResponse, error)
	ModifyTicket(context.Context, *ReservationRequest) (*ReservationResponse, error)
	CancelTicket(context.Context, *ReservationRequest) (*ReservationResponse, error)
	GetAllTickets(context.Context, *EmptyRequest) (*AllTicketsResponse, error)
	mustEmbedUnimplementedTicketReservationServer()
}

// UnimplementedTicketReservationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketReservationServer struct{}

func (UnimplementedTicketReservationServer) ReserveTicket(context.Context, *ReservationRequest) (*ReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveTicket not implemented")
}
func (UnimplementedTicketReservationServer) ModifyTicket(context.Context, *ReservationRequest) (*ReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyTicket not implemented")
}
func (UnimplementedTicketReservationServer) CancelTicket(context.Context, *ReservationRequest) (*ReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTicket not implemented")
}
func (UnimplementedTicketReservationServer) GetAllTickets(context.Context, *EmptyRequest) (*AllTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTickets not implemented")
}
func (UnimplementedTicketReservationServer) mustEmbedUnimplementedTicketReservationServer() {}
func (UnimplementedTicketReservationServer) testEmbeddedByValue()                           {}

// UnsafeTicketReservationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketReservationServer will
// result in compilation errors.
type UnsafeTicketReservationServer interface {
	mustEmbedUnimplementedTicketReservationServer()
}

func RegisterTicketReservationServer(s grpc.ServiceRegistrar, srv TicketReservationServer) {
	// If the following call pancis, it indicates UnimplementedTicketReservationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketReservation_ServiceDesc, srv)
}

func _TicketReservation_ReserveTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketReservationServer).ReserveTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketReservation_ReserveTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketReservationServer).ReserveTicket(ctx, req.(*ReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketReservation_ModifyTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketReservationServer).ModifyTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketReservation_ModifyTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketReservationServer).ModifyTicket(ctx, req.(*ReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketReservation_CancelTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketReservationServer).CancelTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketReservation_CancelTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketReservationServer).CancelTicket(ctx, req.(*ReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketReservation_GetAllTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketReservationServer).GetAllTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketReservation_GetAllTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketReservationServer).GetAllTickets(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketReservation_ServiceDesc is the grpc.ServiceDesc for TicketReservation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketReservation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket_reservation.TicketReservation",
	HandlerType: (*TicketReservationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveTicket",
			Handler:    _TicketReservation_ReserveTicket_Handler,
		},
		{
			MethodName: "ModifyTicket",
			Handler:    _TicketReservation_ModifyTicket_Handler,
		},
		{
			MethodName: "CancelTicket",
			Handler:    _TicketReservation_CancelTicket_Handler,
		},
		{
			MethodName: "GetAllTickets",
			Handler:    _TicketReservation_GetAllTickets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ticket_reservation.proto",
}
